### PR TITLE
Userstory5

### PR DESCRIPTION
**Pull request by rabe200**
database adjustments and logic for history page written , for [userstory 5](https://github.com/rabe200/Capstone_Tarot_App/issues/5)

### CODE REVIEW

**Review by manukao — APPROVED** [review]
Lgtm 👍 

For your information, as I don't know if thats intended or should get fixed in a later user story:

Daily Card CARDLISTHistory work and I can also see the history of the daily cards. However, I can reproduce an issue where I first see the whole list of cards + descriptions even when I followed Daily Card and entered a note.

This mainly happens when clearing the local storage and visiting the website "for the first time".
Sporadically I also get a blank history page.

**Comment by rabe200** [comment]
@manukao not sure if understand correctly. cardlist and history are two seperate buttons. because of no styling... they look like one

**Comment by rabe200** [comment]
@manukao ah i think i now get what you meant with the blankpage. the id of the dailycard only gets stored to localstorage (usedIds) when clicking the submit button at form submit. i was thinking of changing this later one way or the other. not sure yet.

**Comment by manukao** [comment]
aaah i see, makes sense now that there is a space ^^ thx for the explanation, thought it was just one link

**Comment by rabe200** [comment]
i changed it for the qa, but i see you already did it ;)

**Pull request merged**
